services:
  model:
    build: ./model_server
    container_name: llama3-model
    ports:
      - "5000:5000"
    volumes:
      - ./model_server:/app
    environment:
      - MODEL_ID=meta-llama/Meta-Llama-3-8B-Instruct
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia

  jupyter:
    build: ./jupyter
    container_name: jupyter-client
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/base/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: start-notebook.sh --NotebookApp.token=''